version: "3.8"

services:
  redis1:
    image: redis
    container_name: redis_main
    ports:
      - "5000:6379"

  redis2:
    image: redis
    container_name: redis1
    ports:
      - "5300:6379"

  redis3:
    image: redis
    container_name: redis2
    ports:
      - "5400:6379"

  redis4:
    image: redis
    container_name: redis3
    ports:
      - "5500:6379"

  redis5:
    image: redis
    container_name: redis4
    ports:
      - "5600:6379"
